name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

concurrency:
  group: autofix-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: bunver
        run: |
          bun_ver=$(awk '/^bun[[:space:]]+/{print $2; exit}' .tool-versions || true)
          echo "bun_version=$bun_ver" >> $GITHUB_OUTPUT
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.bunver.outputs.bun_version }}
      - run: bun update --no-save
      - run: bun cleanup
      - run: bun run build
      - uses: autofix-ci/action@v1
